# Node.js 
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Job
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.13.0'
        displayName: 'Install Node.js'

- stage: Deploy
  displayName: Deploy Stage
  dependsOn: Build
  jobs: 
   - job: Deploy
     displayName: Deploy Job
     steps:
       - task: Bash@3
         inputs:
          targetType: 'inline'
          script: |
            # Write your commands here      
              echo 'Hello world, hello $(NAME)'